In [2]:
import pandas as pd
import numpy as np

In [2]:
import pandas as pd
print(pd.__version__)

1.2.4


In [7]:
df1=pd.read_excel("FirstDecade (1).xlsx",usecols=['Date','Open','High','Low','Close','Volume'])
tcs_firstDC=df1.to_numpy()
tcs_firstDC

array([[Timestamp('2002-08-12 00:00:00'), 27.78542288474347,
        28.70024426553483, 27.78542288474347, 28.48499298095703, 212976],
       [Timestamp('2002-08-13 00:00:00'), 28.52086875697312,
        28.9782794636968, 27.89305089125358, 28.09933280944824, 153576],
       [Timestamp('2002-08-14 00:00:00'), 28.16211253034757,
        28.16211253034757, 25.6329026031769, 26.16206550598145, 822776],
       ...,
       [Timestamp('2010-12-28 00:00:00'), 448.7846543420418,
        452.5992742187929, 448.33244741254, 450.8099365234375, 1012876],
       [Timestamp('2010-12-29 00:00:00'), 451.8522033325688,
        456.9645433180547, 451.085371536744, 454.9785766601562, 1042370],
       [Timestamp('2010-12-30 00:00:00'), 453.2285208868343,
        461.9981678682445, 453.2285208868343, 460.1891479492188, 3845552]],
      dtype=object)

In [4]:
tcs_firstDC.shape

(2106, 6)

In [5]:
df1=pd.read_excel("secondDecade.xlsx",usecols=['Date','Open','High','Low','Close','Volume'])
tcs_secondDC=df1.to_numpy()
tcs_secondDC

array([[Timestamp('2011-01-03 00:00:00'), 458.9306703004381,
        462.8435561280004, 454.0346425056512, 455.4110412597656, 1405042],
       [Timestamp('2011-01-04 00:00:00'), 457.7116024738174,
        458.5964302802989, 447.5655577575036, 450.1807250976562, 2502868],
       [Timestamp('2011-01-05 00:00:00'), 450.3771736616292,
        458.4979329994586, 449.0007754011484, 455.7647705078125, 3069674],
       ...,
       [Timestamp('2020-12-28 00:00:00'), 2783.004833307803,
        2820.972240865677, 2775.35396091383, 2801.55810546875, 2108994],
       [Timestamp('2020-12-29 00:00:00'), 2792.568580980208,
        2823.172072278621, 2792.568580980208, 2802.6103515625, 1994151],
       [Timestamp('2020-12-30 00:00:00'), 2806.339675193525,
        2819.059296223558, 2775.353737882446, 2782.335205078125, 2637968]],
      dtype=object)

In [6]:
tcs_secondDC.shape

(2462, 6)

# 2.Slicing

In [8]:
tcs_secondDC=tcs_secondDC[0:2106,:]
print(tcs_secondDC)

[[Timestamp('2011-01-03 00:00:00') 458.9306703004381 462.8435561280004
  454.0346425056512 455.4110412597656 1405042]
 [Timestamp('2011-01-04 00:00:00') 457.7116024738174 458.5964302802989
  447.5655577575036 450.1807250976562 2502868]
 [Timestamp('2011-01-05 00:00:00') 450.3771736616292 458.4979329994586
  449.0007754011484 455.7647705078125 3069674]
 ...
 [Timestamp('2019-07-19 00:00:00') 1910.918849556263 1929.319608820166
  1897.578299089934 1910.872802734375 1953177]
 [Timestamp('2019-07-22 00:00:00') 1910.918709291091 1948.134197246915
  1903.374443470383 1941.187866210938 1920167]
 [Timestamp('2019-07-23 00:00:00') 1957.748598546029 1959.680768023928
  1934.287631604897 1943.534057617188 3538588]]


# 3.Arithmetic Operation

In [9]:
result=tcs_firstDC[:,4:5]+2
print(result)

[[30.48499298095703]
 [30.09933280944824]
 [28.16206550598145]
 ...
 [452.8099365234375]
 [456.9785766601562]
 [462.1891479492188]]


In [10]:
result=np.add(tcs_firstDC[:,4:5],2)
print(result)

[[30.48499298095703]
 [30.09933280944824]
 [28.16206550598145]
 ...
 [452.8099365234375]
 [456.9785766601562]
 [462.1891479492188]]


In [11]:
result=np.add(tcs_firstDC[:,1:2],tcs_secondDC[:,1:2])
print(result)                                             

[[486.7160931851816]
 [486.2324712307905]
 [478.53928619197677]
 ...
 [2359.703503898305]
 [2362.77091262366]
 [2410.977119432863]]


In [14]:
for i in range (tcs_firstDC.shape[0]):
    if tcs_firstDC[i,4]-tcs_firstDC[i,1]>0:
        print(tcs_firstDC[i,0],"-->","stock price increased")
    else:
             print(tcs_firstDC[i,0],"-->","stock price decreased")

2002-08-12 00:00:00 --> stock price increased
2002-08-13 00:00:00 --> stock price decreased
2002-08-14 00:00:00 --> stock price decreased
2002-08-15 00:00:00 --> stock price decreased
2002-08-16 00:00:00 --> stock price increased
2002-08-19 00:00:00 --> stock price decreased
2002-08-20 00:00:00 --> stock price increased
2002-08-21 00:00:00 --> stock price decreased
2002-08-22 00:00:00 --> stock price increased
2002-08-23 00:00:00 --> stock price increased
2002-08-26 00:00:00 --> stock price decreased
2002-08-27 00:00:00 --> stock price decreased
2002-08-28 00:00:00 --> stock price increased
2002-08-29 00:00:00 --> stock price increased
2002-08-30 00:00:00 --> stock price increased
2002-09-02 00:00:00 --> stock price decreased
2002-09-03 00:00:00 --> stock price decreased
2002-09-04 00:00:00 --> stock price increased
2002-09-05 00:00:00 --> stock price decreased
2002-09-06 00:00:00 --> stock price decreased
2002-09-09 00:00:00 --> stock price increased
2002-09-10 00:00:00 --> stock pric

2005-01-06 00:00:00 --> stock price increased
2005-01-07 00:00:00 --> stock price increased
2005-01-10 00:00:00 --> stock price decreased
2005-01-11 00:00:00 --> stock price decreased
2005-01-12 00:00:00 --> stock price decreased
2005-01-13 00:00:00 --> stock price decreased
2005-01-14 00:00:00 --> stock price decreased
2005-01-17 00:00:00 --> stock price decreased
2005-01-18 00:00:00 --> stock price decreased
2005-01-19 00:00:00 --> stock price decreased
2005-01-20 00:00:00 --> stock price decreased
2005-01-24 00:00:00 --> stock price decreased
2005-01-25 00:00:00 --> stock price increased
2005-01-27 00:00:00 --> stock price decreased
2005-01-28 00:00:00 --> stock price increased
2005-01-31 00:00:00 --> stock price increased
2005-02-01 00:00:00 --> stock price increased
2005-02-02 00:00:00 --> stock price decreased
2005-02-03 00:00:00 --> stock price decreased
2005-02-04 00:00:00 --> stock price decreased
2005-02-07 00:00:00 --> stock price increased
2005-02-08 00:00:00 --> stock pric

2007-01-10 00:00:00 --> stock price decreased
2007-01-11 00:00:00 --> stock price increased
2007-01-12 00:00:00 --> stock price increased
2007-01-15 00:00:00 --> stock price decreased
2007-01-16 00:00:00 --> stock price decreased
2007-01-17 00:00:00 --> stock price decreased
2007-01-18 00:00:00 --> stock price increased
2007-01-19 00:00:00 --> stock price decreased
2007-01-22 00:00:00 --> stock price increased
2007-01-23 00:00:00 --> stock price decreased
2007-01-24 00:00:00 --> stock price decreased
2007-01-25 00:00:00 --> stock price decreased
2007-01-29 00:00:00 --> stock price decreased
2007-01-31 00:00:00 --> stock price decreased
2007-02-01 00:00:00 --> stock price increased
2007-02-02 00:00:00 --> stock price increased
2007-02-05 00:00:00 --> stock price increased
2007-02-06 00:00:00 --> stock price decreased
2007-02-07 00:00:00 --> stock price increased
2007-02-08 00:00:00 --> stock price decreased
2007-02-09 00:00:00 --> stock price decreased
2007-02-12 00:00:00 --> stock pric

2009-01-21 00:00:00 --> stock price increased
2009-01-22 00:00:00 --> stock price increased
2009-01-23 00:00:00 --> stock price decreased
2009-01-27 00:00:00 --> stock price increased
2009-01-28 00:00:00 --> stock price increased
2009-01-29 00:00:00 --> stock price increased
2009-01-30 00:00:00 --> stock price increased
2009-02-02 00:00:00 --> stock price decreased
2009-02-03 00:00:00 --> stock price increased
2009-02-04 00:00:00 --> stock price decreased
2009-02-05 00:00:00 --> stock price decreased
2009-02-06 00:00:00 --> stock price increased
2009-02-09 00:00:00 --> stock price increased
2009-02-10 00:00:00 --> stock price increased
2009-02-11 00:00:00 --> stock price decreased
2009-02-12 00:00:00 --> stock price decreased
2009-02-13 00:00:00 --> stock price increased
2009-02-16 00:00:00 --> stock price decreased
2009-02-17 00:00:00 --> stock price decreased
2009-02-18 00:00:00 --> stock price decreased
2009-02-19 00:00:00 --> stock price increased
2009-02-20 00:00:00 --> stock pric

In [20]:
result=np.bitwise_and(np.int64(tcs_firstDC[:,4:5]),2)
result

array([[0],
       [0],
       [2],
       ...,
       [2],
       [2],
       [0]], dtype=int64)

# horizontal and veeeeertical stacking of NUmpy Arrays

In [21]:
tcs_firstDC

array([[Timestamp('2002-08-12 00:00:00'), 27.78542288474347,
        28.70024426553483, 27.78542288474347, 28.48499298095703, 212976],
       [Timestamp('2002-08-13 00:00:00'), 28.52086875697312,
        28.9782794636968, 27.89305089125358, 28.09933280944824, 153576],
       [Timestamp('2002-08-14 00:00:00'), 28.16211253034757,
        28.16211253034757, 25.6329026031769, 26.16206550598145, 822776],
       ...,
       [Timestamp('2010-12-28 00:00:00'), 448.7846543420418,
        452.5992742187929, 448.33244741254, 450.8099365234375, 1012876],
       [Timestamp('2010-12-29 00:00:00'), 451.8522033325688,
        456.9645433180547, 451.085371536744, 454.9785766601562, 1042370],
       [Timestamp('2010-12-30 00:00:00'), 453.2285208868343,
        461.9981678682445, 453.2285208868343, 460.1891479492188, 3845552]],
      dtype=object)

In [22]:
tcs_secondDC

array([[Timestamp('2011-01-03 00:00:00'), 458.9306703004381,
        462.8435561280004, 454.0346425056512, 455.4110412597656, 1405042],
       [Timestamp('2011-01-04 00:00:00'), 457.7116024738174,
        458.5964302802989, 447.5655577575036, 450.1807250976562, 2502868],
       [Timestamp('2011-01-05 00:00:00'), 450.3771736616292,
        458.4979329994586, 449.0007754011484, 455.7647705078125, 3069674],
       ...,
       [Timestamp('2019-07-19 00:00:00'), 1910.918849556263,
        1929.319608820166, 1897.578299089934, 1910.872802734375, 1953177],
       [Timestamp('2019-07-22 00:00:00'), 1910.918709291091,
        1948.134197246915, 1903.374443470383, 1941.187866210938, 1920167],
       [Timestamp('2019-07-23 00:00:00'), 1957.748598546029,
        1959.680768023928, 1934.287631604897, 1943.534057617188, 3538588]],
      dtype=object)

In [25]:
result=np.vstack((tcs_firstDC,tcs_secondDC))
print(result.shape)
result

(4212, 6)


array([[Timestamp('2002-08-12 00:00:00'), 27.78542288474347,
        28.70024426553483, 27.78542288474347, 28.48499298095703, 212976],
       [Timestamp('2002-08-13 00:00:00'), 28.52086875697312,
        28.9782794636968, 27.89305089125358, 28.09933280944824, 153576],
       [Timestamp('2002-08-14 00:00:00'), 28.16211253034757,
        28.16211253034757, 25.6329026031769, 26.16206550598145, 822776],
       ...,
       [Timestamp('2019-07-19 00:00:00'), 1910.918849556263,
        1929.319608820166, 1897.578299089934, 1910.872802734375, 1953177],
       [Timestamp('2019-07-22 00:00:00'), 1910.918709291091,
        1948.134197246915, 1903.374443470383, 1941.187866210938, 1920167],
       [Timestamp('2019-07-23 00:00:00'), 1957.748598546029,
        1959.680768023928, 1934.287631604897, 1943.534057617188, 3538588]],
      dtype=object)

In [26]:
result=np.hstack((tcs_firstDC,tcs_secondDC))
print(result.shape)
result

(2106, 12)


array([[Timestamp('2002-08-12 00:00:00'), 27.78542288474347,
        28.70024426553483, ..., 454.0346425056512, 455.4110412597656,
        1405042],
       [Timestamp('2002-08-13 00:00:00'), 28.52086875697312,
        28.9782794636968, ..., 447.5655577575036, 450.1807250976562,
        2502868],
       [Timestamp('2002-08-14 00:00:00'), 28.16211253034757,
        28.16211253034757, ..., 449.0007754011484, 455.7647705078125,
        3069674],
       ...,
       [Timestamp('2010-12-28 00:00:00'), 448.7846543420418,
        452.5992742187929, ..., 1897.578299089934, 1910.872802734375,
        1953177],
       [Timestamp('2010-12-29 00:00:00'), 451.8522033325688,
        456.9645433180547, ..., 1903.374443470383, 1941.187866210938,
        1920167],
       [Timestamp('2010-12-30 00:00:00'), 453.2285208868343,
        461.9981678682445, ..., 1934.287631604897, 1943.534057617188,
        3538588]], dtype=object)

In [28]:
result=np.empty_like(tcs_firstDC)
print(tcs_firstDC.shape)
print(result.shape)

(2106, 6)
(2106, 6)


In [29]:
result


array([[None, None, None, None, None, None],
       [None, None, None, None, None, None],
       [None, None, None, None, None, None],
       ...,
       [None, None, None, None, None, None],
       [None, None, None, None, None, None],
       [None, None, None, None, None, None]], dtype=object)