In [ ]:
import numpy as np

In [ ]:
array1=np.array([1,2,3])
array2=np.array([[3,2,1],[4,5,6]])
array3=np.array([[[3,2,1],[6,5,4],[9,8,7]],[[3,2,1],[6,5,4],[9,8,7]]])
array4=np.array([[1,2,3],[6,5,4]])
#arr = np.zeros((3, 5, 4, 3))
#print(arr)

In [ ]:
print(array1,end="\n\n")
print(array2,end="\n\n")
print(array3,end="\n\n")

[1 2 3]

[[3 2 1]
 [4 5 6]]

[[[3 2 1]
  [6 5 4]
  [9 8 7]]

 [[3 2 1]
  [6 5 4]
  [9 8 7]]]



In [ ]:
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)
#print(arr.ndim)

1
2
3


In [ ]:
sumarr=np.add(array1,array4)
print(sumarr,end="\n\n")
subarr=np.subtract(array1,array4)
print(subarr,end="\n\n")
multarr=np.multiply(array1,array2)
print(multarr,end="\n\n")
dividearr=np.divide(array1,array4)
print(dividearr,end="\n\n")
transarr=np.transpose(sumarr)
print(transarr,end="\n\n")


[[2 4 6]
 [7 7 7]]

[[ 0  0  0]
 [-5 -3 -1]]

[[ 3  4  3]
 [ 4 10 18]]

[[1.         1.         1.        ]
 [0.16666667 0.4        0.75      ]]

[[2 7]
 [4 7]
 [6 7]]



In [ ]:
print ("\nSum of all array "
       "elements: ", dividearr.sum())


Sum of all array elements:  4.316666666666666


In [ ]:
x = np.array([1, 2], dtype = np.int32)   
print("\nForcing a Datatype: ")
print(x.dtype)


Forcing a Datatype: 
int32


In [ ]:
Sqrt = np.sqrt(transarr)
print("\nSquare root of Array1 elements: ")
print(Sqrt)


Square root of Array1 elements: 
[[1.41421356 2.64575131]
 [2.         2.64575131]
 [2.44948974 2.64575131]]


In [ ]:
print("A\n", np.arange(4,10).reshape(2,3) ,"\n")

A
 [[4 5 6]
 [7 8 9]] 



In [ ]:
a = np.mod(transarr, 4) !=0
# This will show element status of satisfying condition
print("\nArray Condition a : \n", a)


Array Condition a : 
 [[ True  True]
 [False  True]
 [ True  True]]


In [ ]:
a=transarr()
np.extract(a>5,transarr)